title: "ラズパイで自宅サーバを立ててみる本"
summary: "一家に一台自宅サーバ！　あなたのお宅にも一台どうです？"
topics: ["Linux", "ubuntu", "raspberrypi", "サーバ構築", "自宅サーバ"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - select-parts
  - check-parts
  - setup-raspi
  - setup-ssh
  - setup-hdd
  - setup-webserver
  - setup-tls
  - setup-tls-certbot
  - setup-nextcloud
  - setup-reverseproxy
  - setup-tmux
  - setup-tailscale
  - setup-dns
  - setup-services
  - ending
  - cmdlist
  - trouble